safe:        true
markdown: kramdown
exclude: [node_modules, bower_components]
kramdown:
  input: GFM
gems:
  - jekyll-redirect-from
  - jekyll-seo-tag
whitelist:
  - jekyll-redirect-from
defaults:
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
title: "Pm Verma"
description: "PM Verma's Website"
url: http://www.pmverma.com
